const FETCH_TODOS = "FETCH_TODOS";
const CREATE_TODO = "CREATE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const DELETE_TODO = "DELETE_TODO";

export { FETCH_TODOS, CREATE_TODO, UPDATE_TODO, DELETE_TODO };
